# --------------------------------------------------------------
#  Application Metadata
# --------------------------------------------------------------
app:
  name: "JIRA MCP SERVER"
  author: "Societe Generale"
  version: "1.0"

# --------------------------------------------------------------
#  Spring Boot Core
# --------------------------------------------------------------
spring:
  profiles:
    active: dev
  ai:
    mcp:
      server:
        sse-endpoint: /sse

# --------------------------------------------------------------
#  Domain / RAG Config
# --------------------------------------------------------------
rag:
  similarity:
    topk: 1
    threshold: 0.5